### PR TITLE
sets AME fuel jar capacity to 1000

### PR DESCRIPTION
**Pull request by zelezniciar1**
## About the PR

- Sets AME fuel jar capacity to 1000.

## Why / Balance

Maps currently in use can depend on AME as primary power source, resulting in frequent power outages (looking at you, Hammu) when AME inevitably runs out before TEG/singulo can be setup. 

## Technical details

- one line C# change 

## Media

n/a

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl: zelezniciar
- tweak: AME fuel jars now have 1000 capacity

### CODE REVIEW

**Review by sleepyyapril — APPROVED** [review]
Fire

**Comment by SsalamethVersaach** [comment]
Change your description to C#!

**Review by SsalamethVersaach — CHANGES_REQUESTED** [review]
Change the description in your PR!

**Comment by zelezniciar1** [comment]
I blame lack of sleep

**Pull request merged**
