### PR TITLE
Revert "Removes the Rat King"

### PR DESCRIPTION
**Pull request by sleepyyapril**
Reverts Grimbly-Station/Grimbly-Station#92

### CODE REVIEW

**Comment by sleepyyapril** [comment]
Merge after poll ends if it says to keep as is.

**Review by zelezniciar1 — APPROVED** [review]
Looks like the community wants it, so they stay in. Merge with #96

**Comment by Tmanzxd** [comment]
YAML Linter fail real

**Comment by zelezniciar1** [comment]
It's literally uncommenting 7 lines! Why is it being angry???

"I HATE YAML LINTER" real

**Pull request merged**
