### PR TITLE
Return Atmos Firedoor Remotes

### PR DESCRIPTION
**Pull request by zelezniciar1**
## About the PR

- Returns Atmos firedoor remotes. 
- TODO: add range limit & allow other remotes firedoor access

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by Tmanzxd** [comment]
Considering that we're in the middle of a rebase is this PR needed?

If not I can close it @zelezniciar1 .

**Comment by stellar-novas** [comment]
It isn't, EE has the old fire door remotes, which used access from the user's ID https://github.com/Simple-Station/Einstein-Engines/pull/491

**Comment by Tmanzxd** [comment]
Got it, I'll go ahead and close this PR then.

**Comment by zelezniciar1** [comment]
Agreed, no longer needed.

**Pull request closed without merging**
