### PR TITLE
Lighthousefix

### PR DESCRIPTION
**Pull request by Mike32oz**
# Description
Fixing minor issues Map lighthouse 

<details><summary><h1>Media</h1></summary>
<p>

Screenshot 2024-10-18 222457
Screenshot 2024-10-18 212616
Screenshot 2024-10-18 232727
Screenshot 2024-10-18 232128
Screenshot 2024-10-18 225145
Screenshot 2024-10-18 224945
Screenshot 2024-10-18 224807
Screenshot 2024-10-18 224443
Screenshot 2024-10-18 223731
Screenshot 2024-10-18 223544
Screenshot 2024-10-18 223429
Screenshot 2024-10-18 223240
Screenshot 2024-10-18 223014
Screenshot 2024-10-18 225419

</p>
</details>

---

# Changelog

:cl: Mike32oz
- Updated:  Remodel Atmos Department 
- Fixed Air in Atmos
- Remove middle doors fire airlocks and added reinforced window in the middle
- Add dock door for Salvage shuttle  (upside down dock doors fixed for the next patch)
- Add a computer console and fire axe for the Chief Engineer Room
- Added plastic eng locker room and more materials in engineer and command storage
- Remove broken down shuttle causing conflict with arrival shuttle.
- Real water was added to the pond near arrival.
- Add an Atmospheric console at the bridge and move station records to the left side.
- Remove backpack add a disabler remove liquor bottle add combat medic kit in Captain's Room
- Add materials and cloning for the Medical Department.
- Fix some walls at the chemistry lab with an additional Chemdispenser, ChemMaster 4000, and hot plate.
- add SMES for gravity generator
- adds materials of 10 at the service room
- Epistemics rejoice I added anti-anomaly zone around the station so no more going to space to look for those.
- Remove the water tank at botany and add the Sink, ChemMaster 400, and windoors.

### CODE REVIEW

**Review by Mike32oz — COMMENTED** [review]
testing Map

**Review by Mike32oz — COMMENTED** [review]
viewed

**Comment by zelezniciar1** [comment]
These changes are quite excellent! The only thing I would ask is reducing the changelog to one line, summarizing the most important changes and the Station name.

**Comment by SsalamethVersaach** [comment]
Please reopen the pull request, since I did an oops. Sorry Mike.

**Comment by Mike32oz** [comment]
I'm still learning how to use this GitHub format please be patient.

**Comment by Mike32oz** [comment]
Maps not working correctly

**Pull request merged**
