### PR TITLE
Removes rodentia sneak, gives them a new toy in return

### PR DESCRIPTION
**Pull request by CometVoid**
# Description

Rodentia sneaking broke with the crawling under tables change, and also just isn't necessary anymore.
Now that they've lost their old special thing, I decided to give them a new special thing!

Their bites now also do 11 structure damage, allowing them to just barely chew through lockers, and chew through 
normal walls extremely slowly (107 bites)

also stopped rodentia taking the small trait, because they fit in duffel bags already

---

# Changelog

:cl:
- tweak: Rodentia can no longer take the small trait, because they have it innately
- add: Rodentia can now chew through lockers, and very slowly chew through walls (107 bites)
- remove: Rodentia has had their sneak ability removed, because everyone can hide under tables now.

### CODE REVIEW

**Comment by zelezniciar1** [comment]
@CometVoid Just curious, how many bites to get through a locker?

**Comment by CometVoid** [comment]
> @CometVoid Just curious, how many bites to get through a locker?

I don't remember entirely. I think it was like 16? maybe 18? it's slower than breaking in with a baseball bat

**Comment by Tmanzxd** [comment]
If I recall right a toolbox takes 13 hits to break a locker as well. So long as its less hits than a toolbox I think its good for adding in. If it becomes a problem we can change it later.

**Comment by CometVoid** [comment]
> If I recall right a toolbox takes 13 hits to break a locker as well. So long as its less hits than a toolbox I think its good for adding in. If it becomes a problem we can change it later.

It only barely breaks the flat damage reduction threshold on a locker by 1 damage point, and it's structural anyways so it doesn't become horrifying in pvp

**Comment by Tmanzxd** [comment]
Yea should be good then I see no issues with it.

**Review by Tmanzxd — APPROVED** [review]

**Review by zelezniciar1 — APPROVED** [review]

**Pull request merged**
