### PR TITLE
Fix Guidebook Parse Error.

### PR DESCRIPTION
**Pull request by Tmanzxd**
# Changed the slashes to letters to prevent parsing errors for the Grimbly Guidebook Rules.

- fix: Fixed some parsing errors upon build.

### CODE REVIEW

**Review by zelezniciar1 — APPROVED** [review]
Seems legit

**Comment by Tmanzxd** [comment]
Parse error is gone, debug fails at the logmanager but everything else runs.

**Comment by zelezniciar1** [comment]
Looks like it is failing because it's running too long (28 minutes, wow), I've seen the same issue on upstream PR's. Something's hinky

**Comment by Tmanzxd** [comment]
April let me know it was with loadouts v4, this should be good to merge.

**Comment by sleepyyapril** [comment]
It's taking so long because of the fails, we just gotta focus those.

**Review by sleepyyapril — APPROVED** [review]

**Pull request merged**
