### PR TITLE
Change default Borg laws to Asimov

### PR DESCRIPTION
**Pull request by TwoDucksOnnaPlane**
# About PR

Added and changed default lawset for Cyborgs to the Asimov++ lawset from [TGStation](https://tgstation13.org/wiki/AI_modules#Station-Sided_Laws).
# Why / Balance

A "small" part in giving the species different strengths and weaknesses.

Whether this needs to be reverted or laws amended will entirely depend on if players can handle being given free agency to help/hinder other species besides humans without the guide rails of Crewsimov holding them.
# Technical Details

Added a couple lines, and changed the default lawsets in the areas needed.
# Changelog

:cl:
- add: Added Asimov lawset for Cyborgs.
- tweak: Changed default lawset for Cyborgs to be Asimov laws, from Crewsimov.

### CODE REVIEW

**Comment by TwoDucksOnnaPlane** [comment]
minor typo in the comment in silicon-laws.yml but i cannot care since it's never shown to the end user :trollface:

**Comment by Tmanzxd** [comment]
We do appreciate the Asimov lawset, but idk if we're gonna want it as the default. That's something that will need ran by the staff and community.

We can totally keep this in as an AI lawset for someone to swap out later in game though.

**Comment by zelezniciar1** [comment]
+1 for having this as a lawset option, but not as default.

**Comment by stellar-novas** [comment]
Won't this break emagging since "crew" isn't defined and emagging just changes the definition of crew?

**Comment by TwoDucksOnnaPlane** [comment]
image
EMAGging borgs still works as intended.

**Comment by SsalamethVersaach** [comment]
I'm also for internal and external discussion on this, as I feel we have a decent amount of players who are not human, and this could allow for inert speciesism, which (as far as I know) is not the direction this server wants to go.

**Comment by sleepyyapril** [comment]
Difficult situation: allows for a lot of speciesism, which I don't want. If you're going to be hating someone, at least have a good reason that isn't something they just happen to be.

**Comment by Tmanzxd** [comment]
After staff discussion, we are not looking to merge this as this goes against our "no-speciesism" focus of this server. However, Singularity Network might want this lawset so I recommend talking to them on their discord.

**Pull request closed without merging**
