### PR TITLE
Station Wide DESTRUCTION

### PR DESCRIPTION
**Pull request by SsalamethVersaach**
## About the PR

I re-added Station Wide DESTRUCTION!!!!

## Why / Balance

We want more chaos in our spessgame.

## Technical details

Changed two lines of code.

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None, I hope.

**Changelog**

:cl:
- add: Added Nikola Tesla, and Singulo Loose back to artifact pool

### CODE REVIEW

**Comment by zelezniciar1** [comment]
"YES teslaloose" engineers in shambles

**Comment by sleepyyapril** [comment]
This is a horrible idea pfft

**Comment by SsalamethVersaach** [comment]
> This is a horrible idea pfft

You should totally review the PR

**Comment by sleepyyapril** [comment]
I don't like the idea of allowing random, unchangeable and unavoidable destruction in an MRP setting personally so I'll wait until Tmanz or even Ponky comments

**Review by sleepyyapril — APPROVED** [review]
Lets see how this goes

**Comment by zelezniciar1** [comment]
+1 for inculding this

You have to be pretty down far the Artifact node tree to trigger these, and having the extremely rare round end in massive chaos isn't neccessarily a bad thing. MRP is about telling stories, not just "is it balanced". 

And, of course, if people feel that it happens too often, we can (1) make it rarer or (2) remove it outright.

**Comment by Tmanzxd** [comment]
This looks fine, we're gonna go ahead and merge this in. we'll pin up this PR under the PR watch under the staff forum in case we need to rebalance it.

**Review by Tmanzxd — APPROVED** [review]

**Pull request merged**
